import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/nav/navbar/Navbar";
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Suspense fallback={<div>Loading...</div>}>
          <Navbar auth={auth} />
          {auth}
          {children}
        </Suspense>
      </body>
    </html>
  );
}
