import type { Metadata } from "next";
import "./globals.css";
import NavbarDescktop from "@/components/nav/navbarDescktop/NavbarDescktop";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarDescktop auth={auth} />
        {children}
      </body>
    </html>
  );
}
